site_name: Dashboad Builder Documentation

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Calculation Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
  - Components: components.md