site_name: Dashboad Builder 

theme:
  name: "material"
  features:
    - content.code.copy

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Welcome: index.md
  - Getting Started: tutorials/getting-started.md
  - API: 
    - Configuration: classes/configuration.md
    - Inputs: 
        - Classes: classes/component_input.md
        - Templates: jinja/input.md
    - Outputs: 
        - Classes: classes/component_output.md
        - Templates: jinja/output.md
    - Layouts: 
        - Classes: classes/layouts.md
        - Templates: jinja/layout.md
